name: Build, push, and deploy app

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '22'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-push
        with:
          team: tilleggsstonader
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/gcp-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}