name: Build, push, and deploy app

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-push
        with:
          team: tilleggsstonader
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/gcp-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}