name: Build, push, and deploy app

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: tilleggsstonader
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Post deploy failures to Slack
        if: github.ref == 'refs/heads/main' && failure()
        run: |
          curl -X POST --data "{\"text\": \"Build av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/gcp-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}
      - name: Post deploy failures to Slack
        if: github.ref == 'refs/heads/main' && failure()
        run: |
          curl -X POST --data "{\"text\": \"Deploy av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
